// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1iivcd6HFx7Q5UkD71YTYEAhgU1jMu0A',
    appId: '1:859349806124:android:5b3f4e4eb11f44fa7e7589',
    messagingSenderId: '859349806124',
    projectId: 'backpack-ba3ca',
    storageBucket: 'backpack-ba3ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC3U8HX1cKdPI4qOTvY_5SJi3fut_kcz8',
    appId: '1:859349806124:ios:57194b2979a1ea2d7e7589',
    messagingSenderId: '859349806124',
    projectId: 'backpack-ba3ca',
    storageBucket: 'backpack-ba3ca.appspot.com',
    iosBundleId: 'com.example.backend',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYRz0GiponFsPNuXDYBMHR9uNHQ8mgaS0',
    appId: '1:859349806124:web:6e3ab0532763916b7e7589',
    messagingSenderId: '859349806124',
    projectId: 'backpack-ba3ca',
    authDomain: 'backpack-ba3ca.firebaseapp.com',
    storageBucket: 'backpack-ba3ca.appspot.com',
    measurementId: 'G-KCNRKXQHKN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC3U8HX1cKdPI4qOTvY_5SJi3fut_kcz8',
    appId: '1:859349806124:ios:57194b2979a1ea2d7e7589',
    messagingSenderId: '859349806124',
    projectId: 'backpack-ba3ca',
    storageBucket: 'backpack-ba3ca.appspot.com',
    iosBundleId: 'com.example.backend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYRz0GiponFsPNuXDYBMHR9uNHQ8mgaS0',
    appId: '1:859349806124:web:32caa636f0873e787e7589',
    messagingSenderId: '859349806124',
    projectId: 'backpack-ba3ca',
    authDomain: 'backpack-ba3ca.firebaseapp.com',
    storageBucket: 'backpack-ba3ca.appspot.com',
    measurementId: 'G-TN1SPZV5C1',
  );

}